name: test_ml_transforms

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    container:
      image: ros:jazzy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y python3-colcon-common-extensions python3-rosdep

      - name: rosdep install
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          rosdep update
          rosdep install --from-paths ROS2_ws/ml_pkgs/ml_transforms --ignore-src -r -y

      - name: Build ml_transforms
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --packages-select ml_transforms --base-paths ROS2_ws/ml_pkgs

      - name: Test ml_transforms
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon test --packages-select ml_transforms --base-paths ROS2_ws/ml_pkgs
          colcon test-result --verbose
